
spring:
  datasource:
    url: ${DB_URL_Dev}
    driver-class-name: org.h2.Driver
    username: ${DB_USERNAME_Dev}
    password: ${DB_PASSWORD_Dev}
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect