spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/citronix
    username: postgres
    password: 2024
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect


 ## DB_URL_Prod=jdbc:postgresql://localhost:5432/citronix
 ## DB_USERNAME_Prod=postgres
  ##DB_PASSWORD_Prod=2024

    ## url: ${DB_URL_Prod}
   ## username: ${DB_USERNAME_Prod}
   ## password: ${DB_PASSWORD_Prod}