spring:
  application:
    name: citronix
  profiles:
    active: prod
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  liquibase:
    enabled: false
server:
  port: 8086
  error:
    include-stacktrace: never

